apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: dotnet-todos-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnet-todos-api
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@ssh.dev.azure.com/v3/doddatvmware/tap-lab/gitops-dotnet-todos
      ref:
        branch: main
    subPath: employee-todo-list-api